### ISSUE TITLE
android app not useful in forced landscape mode

### ISSUE THREAD

**Issue by ImDroided** [nickdaria/TzumiMagicTV-RTLSDR#2]
So since you already took the app apart any chance on making it landscape friendly? basically the app cuts off the entire bottom of itself when on a device that is forced landscape i.e. my android head unit in my car. would be awesome to keep one of these in my car but the app is useless in landscape mode. need to find a way to make the app scroll-able while in landscape.

**Comment by nickdaria** [comment]
Interesting idea. That will be tough given how the code is obfuscated. We
have, however figured out how the server works, so we could potentially
make an aftermarket app. Maybe once we unlock the sdr functionality, we can
look into the idea.

**Comment by ImDroided** [comment]
This should just be a flag set in the manifest file

**Comment by ImDroided** [comment]
Something like this might work

https://stackoverflow.com/questions/21056625/android-relativelayout-wont-scroll-when-in-landscape-mode

**Comment by ImDroided** [comment]
Also if you send me the Android project folder I could take a peek at it

**Comment by nickdaria** [comment]
The APK should be available in the repo. Use JARX to decompile it.
