### ISSUE TITLE
Firmware versions

### ISSUE THREAD

**Issue by parkerlreed** [nickdaria/TzumiMagicTV-RTLSDR#3]
I have run across a device with firmware 2.8. I have noticed some random times where `atsc_server` cannot initialize the hardware and fails (Even on clean boot). Would be good if we can find the 3.0 update package (or some way to create one from an existing 3.0 device)

**Comment by nickdaria** [comment]
It appears they closed the update server so I’m not confident there are any copies of the 3.0 update file. Maybe if we pull the firmware from a 2.8 and 3.0 stock device we can compare the differences.

**Comment by parkerlreed** [comment]
There are mtd dumps now https://github.com/ozpaulb/tzumi_utils/tree/master/mtd_dumps

**Comment by nickdaria** [comment]
I am going to close this issue as it is now your project. Please let me know when you have progress on the update file so I may reference it here.
