### ISSUE TITLE
UART pinout

### ISSUE THREAD

**Issue by parkerlreed** [nickdaria/TzumiMagicTV-RTLSDR#6]
https://github.com/nickdaria/TzumiMagicTV-RTLSDR/blob/master/hardware/README.md#serial

As far as I'm aware those aren't inverted in the original picture. TX is in the middle which you then hook the RX of your adapter to. So your "fixed" version is correct if you are thinking from the cable's point of view but isn't the actual pin assignment on the device.

https://i.imgur.com/o5jlu2J.jpg

**Comment by nickdaria** [comment]
Yeah, I was just shooting for a user friendly pic. It can be confusing for beginners when you throw around Tx and Rx reversed.

**Comment by nickdaria** [comment]
NOTE: Feel free to note this in a modified image. I have added you as a collaborator.

**Comment by parkerlreed** [comment]
Ok cool didn't know what you wanted to do there. Thanks.
