### ISSUE TITLE
Wiki Content

### ISSUE THREAD

**Issue by nickdaria** [nickdaria/TzumiMagicTV-RTLSDR#7]
When you get a chance, consider setting up the GitHub wiki. The readme.md files are great for navigating the repo, but an informative wiki that simply includes instructions (EXAMPLE: tzupload or your channel script) to popular programs. Also, you can embed binary download links. Let me know if anyone would like to take this on.

**Comment by nickdaria** [comment]
@parkerlreed Any updates?

**Comment by parkerlreed** [comment]
I haven't had any time to work on this. Devices have been sitting in my bag doing nothing.

The existing files in the repo already explain it fairly well.
